# pkio config file

# browser: google-chrome

# See https://github.com/makeplus/makes for available modules.
# makes:
# - node
# - perl
# - python

# read-only:
# - ~/.npmrc
# - ~/.pip/pip.conf
# - ~/.local/lib

# read-write:
# - node_modules

# net:
#   domains:
#   - registry.npmjs.org
#   - pypi.org
#   - crates.io
#   ports:
#     listen:
#     - 3000
#     open:
#     - 5173

# env:
#   SOME_VAR: some-value

# path:
# - /usr/bin

# makefile: |
#   CUSTOM-VAR := value
