--- !ys-0

config-dir =:: ~/.config/pkio/cache/claude
# pkio config for claude

--- !ys:
browser: google-chrome

cmd-args:
- --dangerously-skip-permissions

env:
  CLAUDE_CODE_DISABLE_TERMINAL_TITLE: 1
  CLAUDE_CONFIG_DIR:: config-dir

read-write:
- ! config-dir + '/'
- /tmp
- /tmp/claude-$(shell id -u)
- ~/.cache/makes
- $(PKIO_CACHE)
- ~/.claude/plugins/

read-only:
- ~/.codex/AGENTS.md
- ~/.ssh/known_hosts
- /proc
- /usr/bin
- /usr/local/bin
- /usr/libexec
- /usr/include
- /etc/gitconfig
- /etc/passwd
